### ISSUE TITLE
frontend: add share icon in the notes in particular box section

### ISSUE THREAD

**Issue by Priyanshu-Singh-1** [Rajat2024/NoteBook#1]

**Comment by Priyanshu-Singh-1** [comment]
I am willing to work on this issue. So can you assign this issue to me?

**Comment by Rajat2024** [comment]
Ok

**Comment by Rajat2024** [comment]
ok
I assigned you

**Comment by Rajat2024** [comment]
Please tell that you are working on this issue or not 😔 @Priyanshu-Singh-1
