### ISSUE TITLE
Feature : Search bar Feature for the webapp 

### ISSUE THREAD

**Issue by Sachittarway** [Rajat2024/NoteBook#10]
Will add this Feature So that it may ease the use of the webapp

**Comment by Sachittarway** [comment]
@Rajat2024  assign me to this !!

**Comment by Rajat2024** [comment]
ok work on it

**Comment by abrehan2** [comment]
pls assign me the task too!!

**Comment by abrehan2** [comment]
@Rajat2024 

Sir, I'm working on another issue, you can assign this to someone else. Thank you!
