### ISSUE TITLE
Adding background effect to login and signup buttons

### ISSUE THREAD

**Issue by mukul314** [Rajat2024/NoteBook#105]
**Is your feature request related to a problem? Please describe.**
We can add a nice background colour on the login and signup buttons when hovered upon

**Describe the solution you'd like**
This will make the website more eye catchy

@Rajat2024  sir, I'd like to work on this if you approve.

See the below video for more context

https://github.com/Rajat2024/NoteBook/assets/76463001/655dddda-a537-4578-8b9b-37d1de119e5e

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.
