### ISSUE TITLE
[Style]: improving styling of sing up and log in forms( GSSOC' 23)

### ISSUE THREAD

**Issue by DurgaSanthosh** [Rajat2024/NoteBook#110]

**Comment by Ujala-2110** [comment]
I am a gssoc'23 contributor and i want to add this feature please assign to me ,
Thank you

**Comment by chiki012** [comment]
Hello, I have already done these types of pages in my personal project,  so I easily handle these issues. please assign me this issue.
I'm GSSOC'23 contributor.
