### ISSUE TITLE
Add Feature - Authentication by Google account

### ISSUE THREAD

**Issue by Santosh7017** [Rajat2024/NoteBook#111]
<img width="958" alt="image" src="https://github.com/Rajat2024/NoteBook/assets/73546536/3eb83271-a1d0-4c8f-b464-9dcb8c6e7bfb">

Benefits :-

This is one of the most authentic way to authenticate user
It will be very convenient for regular users.
It is reliable and secure
Most of the users trust on google
It fast and responsive
Approach:
To add this feature, I propose the following steps:

To implement this feature we will use Passport which is authentication middleware for Node.js
We will setup passport google oauth2 strategy
We will generate a OAuth client id
then verify the user using Google Account
Save the user data into database
Additional Information:

As a proud participant of GSSOC3, armed with my extensive experience in similar projects, I possess the unwavering confidence to skillfully incorporate this feature .

Thank you for considering my involvement in resolving this issue. I am eager to collaborate with the team to ensure the successful implementation of the necessary improvements.

**Comment by Apreksha** [comment]
Hey @Rajat2024, I'm a GSSoC'23 contributor and a full stack developer. I can add the Google authentication feature. Could you please assign this task to me?

**Comment by prithidevghosh** [comment]
Hi , I can help with creating auth with google , facebook & twitter . Please assign this to me under gssoc'23
