### ISSUE TITLE
[UI] - Improve UI of Add Note Page

### ISSUE THREAD

**Issue by Santosh7017** [Rajat2024/NoteBook#112]
<img width="956" alt="image" src="https://github.com/Rajat2024/NoteBook/assets/73546536/bc59f6ed-512d-4801-a073-30b68c2d6a6c">

I have ideas to make UI more interactive and eye catchy . 
As a proud participant of GSSOC3, armed with my extensive experience in similar projects, I possess the unwavering confidence to skillfully incorporate this feature .

Thank you for considering my involvement in resolving this issue. I am eager to collaborate with the team to ensure the successful implementation of the necessary improvements.

**Comment by dhrumishah** [comment]
Hey! What's the update on this issue? Can I work on this?

**Comment by bhoomikhurana** [comment]
Has this work been done?I'd like to take this issue

**Comment by Rajat2024** [comment]
@Santosh7017

**Comment by Santosh7017** [comment]
working on this issue
