### ISSUE TITLE
Changing the UI(minimal changes) of the about page

### ISSUE THREAD

**Issue by mukul314** [Rajat2024/NoteBook#114]
The current About page is a very simple one, I added some box shadow to it, made the container rounded and added some hover effects which make it more attractive.

See the below video:

https://github.com/Rajat2024/NoteBook/assets/76463001/6c8c0d92-eefa-4512-9da9-ea3825d558dd

@Rajat2024 , please assign me this issue under GSSOC'23

**Comment by Apreksha** [comment]
Hey @Rajat2024, I'm a GSSoC'23 contributor and a full stack developer. I can enhance the appearance of the about us page. Could you please assign this task to me?

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.
