### ISSUE TITLE
No length on password

### ISSUE THREAD

**Issue by AkankshaGawade** [Rajat2024/NoteBook#137]
**Describe the bug**
Hey when I try to set the password while creating account I noticed that you haven't kept any password limit.You need to decrease password length :There are two reasons for limiting the password size. For one, hashing a large amount of data can cause significant resource consumption on behalf of the server and would be an easy target for Denial Of Service attack.
Normally all sites have a password minimum to maximum length like 72 characters limit or 48 limit to prevent Denial Of Service attack. in my sql but in weblate registration page there are no limitation. Let me know if you need any more details.
This is typically not DoS, but a vulnerability which may lead to DoS attack.

**To Reproduce**
1. Go to 'https://mern-notebook.onrender.com/login'
2. Click on 'Login'
3. Enter password

**Expected behavior**
As the response is seen, the server might not be able to handle such lengthy passwords coming from different machines simultaneously. The attacker can perform a DDOS attack by using this vulnerability. So there should be some length on password.

**Screenshots**
![Screenshot 2023-05-27 194845](https://github.com/Rajat2024/NoteBook/assets/87490936/931eaf58-6729-4c80-8202-fc2d3cb6c9e1)

Assign this issue to me under gssoc 23.

**Comment by kash5811** [comment]
assign this issue to me
