### ISSUE TITLE
fix : width issues 

### ISSUE THREAD

**Issue by rohitroy-github** [Rajat2024/NoteBook#164]
The page forms in the login and signup pages look too wide. It should be a bit less according to standard authentication widths. If you agree, I would like to improve this in accordance with Hacktoberfest !

![image](https://github.com/Rajat2024/NoteBook/assets/68563695/bfac9106-6805-464f-964a-16cb813f0e0c)

![image](https://github.com/Rajat2024/NoteBook/assets/68563695/72474611-2d39-4c10-add2-f50b7a75a2e9)

**Comment by rohitroy-github** [comment]
@Rajat2024 which Mongo URL i need to paste in here >>> 
![image](https://github.com/Rajat2024/NoteBook/assets/68563695/3438077c-7f43-40d1-973b-4cf9abeeab49)
???

**Comment by Rajat2024** [comment]
you ave to use localhost mongo
