### ISSUE TITLE
[BUG] Name of authenticated user disappears from top navbar

### ISSUE THREAD

**Issue by fjuren** [Rajat2024/NoteBook#188]
When logged in, my name correctly displays next to 'Welcome'. If I create a new tab, the name is lost from the navbar. See sample video.

Expected result: Name should show next to 'Welcome' when new tab is opened.
Actual result: Name does not show next to 'Welcome' when new tab is opened.

https://github.com/Rajat2024/NoteBook/assets/65582950/8a059a06-1a73-4c62-a062-00d1a43ff551

**Comment by tushar-daiya** [comment]
Can I work on this?

**Comment by fjuren** [comment]
@tushar-daiya I found the issue this morning. Should be able to fix it today 👍
