### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Ahtaxam** [Rajat2024/NoteBook#19]
**Describe the bug**
when a user signup. then it take unexpected time also error in browser and some console.log() statement. need to fix server side code.

Note: i would like to work on this issue.

![Screenshot from 2023-05-20 00-01-30](https://github.com/Rajat2024/NoteBook/assets/64573767/7b919899-280d-4fdf-8985-f50820927dfa)

**Comment by Rajat2024** [comment]
but there is no error on my browser 
Please tell me which browser you are using

**Comment by Ahtaxam** [comment]
I used Chrome Browser

**Comment by Rajat2024** [comment]
but in my browser there is no error

**Comment by Rajat2024** [comment]
ok i will assign you

**Comment by Ahtaxam** [comment]
@Rajat2024 I Corrected all errors and removed log statements. 
but now i have question that there is no option of user who forgot his password. we should also implement that functionality, so should i start working on this or for that feature open new issue.

**Comment by Ahtaxam** [comment]
And also should working on new UI to take this project to next level
