### ISSUE TITLE
Adding Linear gradient in background instead of background image.

### ISSUE THREAD

**Issue by ojasaklechayt** [Rajat2024/NoteBook#2]
I want to update index.css and the website by adding a linear gradient instead of adding a background image. Can you please assign it to me?

**Comment by ojasaklechayt** [comment]
I think the linear gradient will look much better than the current background image as it is not of good quality. 
Also, just a request, I am coming from social winter of code.

**Comment by Rajat2024** [comment]
ok you can start now 
if you have any issue than you can contact me on linkedin

**Comment by ojasaklechayt** [comment]
Okay Thankyou

**Comment by Rajat2024** [comment]
@ojasaklechayt your contribution was great

**Comment by ojasaklechayt** [comment]
Thankyou 😄

**Comment by ojasaklechayt** [comment]
By the way, this will be counted in SWOC right ?

**Comment by Rajat2024** [comment]
Yes

**Comment by ojasaklechayt** [comment]
Where can I check dark mode version? I can't find the options on the web

**Comment by Rajat2024** [comment]
[darkmode extension link](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)

add to crome then see

**Comment by ojasaklechayt** [comment]
Hello, I have done background-repeat to none. So, now it will look better. And for navbar and form to be dark, that's because we haven't added darkmode personally.  It is done through the extention so, it might not be perfect with it.

**Comment by ojasaklechayt** [comment]
I will create the pull request

**Comment by Rajat2024** [comment]
Ok
