### ISSUE TITLE
Add a 404 page [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [Rajat2024/NoteBook#21]
Add a 404 page
Can you assign this to me, I want to work on this under GSSoC'23
![image](https://github.com/Rajat2024/NoteBook/assets/76804228/fe54c0d8-1767-4158-aaf3-8638673ab7b2)

**Comment by Sukhendu2002** [comment]
Hey @Rajat2024  can you add GSSoC'23 lebel

**Comment by Sukhendu2002** [comment]
Can i close this issue now

**Comment by Rajat2024** [comment]
ok

**Comment by Rajat2024** [comment]
closed
