### ISSUE TITLE
height of notes are not same

### ISSUE THREAD

**Issue by 007xylogramori** [Rajat2024/NoteBook#27]
the height of all the notes is not same.

I would tackle the issue by changing the css of noteitem component

![screencapture-localhost-3000-notes-2023-05-20-13_41_33](https://github.com/Rajat2024/NoteBook/assets/119863801/d429776e-f16a-4e79-a312-fe2b614f0198)

**Comment by adityavpawar** [comment]
I am interested in this issue. please assign it to me.
