### ISSUE TITLE
For Backend devloper -- if anyone want to improve the bug in login portal then message to me than i will assign you work

### ISSUE THREAD

**Issue by Rajat2024** [Rajat2024/NoteBook#3]
bug is if anyone want to login with wrong password than it login successfully
so please correct it

**Comment by MaYaNkKashyap681** [comment]
Assign this to me please.

**Comment by dheerajchhatanidc** [comment]
@Rajat2024 I would like to work on it

**Comment by Rajat2024** [comment]
@MaYaNkKashyap681 okk you can work
