### ISSUE TITLE
display of The user name in the navbar

### ISSUE THREAD

**Issue by 007xylogramori** [Rajat2024/NoteBook#36]
**Is your feature request related to a problem? Please describe.**
there's no way for the user to see if he is logged in or not , we should display the current users name in the navbar 
![Screenshot (131)](https://github.com/Rajat2024/NoteBook/assets/119863801/3ac30f29-50f8-418c-b88f-5126ea8a4eaa)

Please assign this issue to me as apart of GSSOC'23

**Comment by adityavpawar** [comment]
Please assign this issue  I can solve this  issue

**Comment by abcxyz31** [comment]
i can contribute to this
