### ISSUE TITLE
Create a New UI/UX for the website 

### ISSUE THREAD

**Issue by niranjan-kurhade** [Rajat2024/NoteBook#38]
I'll create a new UI/UX design for the website.
I'll deliver a Figma File consisting of the new layout for the website, such as font improvement, navbar improvement, the structure of the website, and colors on the website according to proper color theory. 
Many things can be improved on the website.
Can you please approve this issue and assign it to me under GSSOC'23?

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by niranjan-kurhade** [comment]
> I would like to contribute to this issue as a part of @GSSOC'23 Please assign it to me. Thank you.

Hey @Sathvik902, I have already requested to assign it to me. Can you please work on other issues?

**Comment by Rajat2024** [comment]
Please give which type of UI/UX you will use 
Please show demo @niranjan-kurhade @Sathvik902 

If it was better than present then I will assign

**Comment by Sathvik902** [comment]
@Rajat2024 ,
For example I can add something like this for Add Notes page:

![image](https://github.com/Rajat2024/NoteBook/assets/92165565/d65b0c96-19c0-44c7-8010-9fd316918945)


And Add a Footer like:

![image](https://github.com/Rajat2024/NoteBook/assets/92165565/e87eb6f6-4f01-4b70-8f27-2d2cc4c68621)

**OR**

![image](https://github.com/Rajat2024/NoteBook/assets/92165565/45a9b5fc-0557-4ddc-bc73-e7d29e63ccad)


Please assign me @Rajat2024
Thank you!

**Comment by Sathvik902** [comment]
@Rajat2024 , At present, the background image is repeating.. It will be fixed and will look cool by changing it to the above.
Thanks.
