### ISSUE TITLE
Text is too small at the login page.

### ISSUE THREAD

**Issue by prernadabi23** [Rajat2024/NoteBook#41]
Below Login -` don't have an account` and `Signup` font size is too small and not easily readable.

Changes:
We can increase the font-size.

![Screenshot from 2023-05-20 17-01-10](https://github.com/Rajat2024/NoteBook/assets/104578155/b87dd140-a03c-4e9d-82d2-f025ffacca57)

**Comment by Sukhendu2002** [comment]
Can you assign this to me, I want to fix it

**Comment by akhilsai0099** [comment]
Can you assign this issue to me
