### ISSUE TITLE
Documentation of the About section

### ISSUE THREAD

**Issue by harshita-kaushik2** [Rajat2024/NoteBook#43]
### Description:
The about section gets the user that is using the website to stick around. And the documentation of About section is pretty vague and not fun to read in the present state.

### Expected Outcome:
With the right inputs the About section can provide utility ideas to the user.

Owing to my past experience of content creation, I would love to work on this. 
Hence I request you to assign the issue to me as a GSSoC 2023 contributor. Thank you :)

**Comment by Rajat2024** [comment]
Please send what you want add @harshita-kaushik2

**Comment by harshita-kaushik2** [comment]
Hey @Rajat2024 ,
Should I send you my PR on that so that you can judge if you want to merge it or not ?

The idea is to make the text more user appealing and enumerate the utility of the website in a fun way.
