### ISSUE TITLE
ADD NOTE button is not working ,it is not adding note in "your note" page

### ISSUE THREAD

**Issue by Meenakshiratnawat** [Rajat2024/NoteBook#45]
**Describe the bug**
ADD NOTE button is not working ,it is not adding note in "your note" page

**To Reproduce**
1. Go to  add note 
2. Click on  add note
3. when you see your note no note is added 

**Expected behavior**
your note should show your notes whenever you add a new note, I can improve this functionality and save note in your note page locally .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 

**Smartphone (please complete the following information):**

**Additional context**
Gssoc'23

**Comment by Uma-Shankar0927** [comment]
I am proficient in MERN stack development. I can fix this. So, can you assign this to me?

**Comment by Rajat2024** [comment]
@Meenakshiratnawat  add screenshot
In my browser it is working
