### ISSUE TITLE
Change the design of the login page.

### ISSUE THREAD

**Issue by JatinBisht2308** [Rajat2024/NoteBook#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bhoomigupta1406** [comment]
Hey @Rajat2024 i want to contribute in this under GSSOC.

**Comment by JatinBisht2308** [comment]
@bhoomigupta1406 this issue is already assigned to me try finding other ones.
