### ISSUE TITLE
Styling of navbar 

### ISSUE THREAD

**Issue by Nitish-hack** [Rajat2024/NoteBook#53]
styling of Navbar is very basic , it should be more attractive and user friendly

**Comment by Nitish-hack** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by Nitish-hack** [comment]
To style navbar and make it look attractive , i have to change the colour of it because the present colour is dull , but if i change the colour it would not match with the add note page should  i work on UI as well?

**Comment by Rajat2024** [comment]
Yes

**Comment by Nitish-hack** [comment]
yes what? change the colour of ui or not

**Comment by ptharshit** [comment]
I have to work on this issue under GSSoC'23. Please assign me this.
