### ISSUE TITLE
Verify Email

### ISSUE THREAD

**Issue by nwokporochukwuebuka** [Rajat2024/NoteBook#58]
**Is your feature request related to a problem? Please describe.**
Because of the previous issue about users forgetting their password, We need a way to ensure that the email that has been provided to us is very correct. That calls for the verified email. This helps us to ensure that a user inputs the correct email. 

**Describe the solution you'd like**
The solution to this is to send a unique token to the user's registered email and once the user inputs this email, the user is verified and can be allowed to perform whatsoever action on the website.

This calls for a new column to be added to the users table called `isEmailVerified` which is a boolean data

**Comment by bhoomigupta1406** [comment]
Hey @Rajat2024 i want to contribute in this under GSSOC.

**Comment by Rajat2024** [comment]
you can work on this

**Comment by Chukwuebuka2** [comment]
@Rajat2024 I have done this more than 2 weeks ago and submitted a pull request, I don't know why you have not merged or gotten back. 

Thanks..

**Comment by Rajat2024** [comment]
@Chukwuebuka2 I see your Pull request was on another topic 

can you send the link of pull request if your pull request on above topic

**Comment by Chukwuebuka2** [comment]
I submitted all at once success I was the same person working on it. 

Aside that, I'm surprised that you saw this issue for over two weeks and didn't respond. It can be very discouraging.
