### ISSUE TITLE
If anyone want to add some more function then message me I will assign you for that work

### ISSUE THREAD

**Issue by Rajat2024** [Rajat2024/NoteBook#7]

**Comment by Sachittarway** [comment]
I can add search bar for searching the notes. Assign this to me @Rajat2024 .

**Comment by Rajat2024** [comment]
Yes @MaYaNkKashyap681

**Comment by Rajat2024** [comment]
@Sachittarway create an new issue for topic and I will assign you 
Then you can start

**Comment by MaYaNkKashyap681** [comment]
Do you also have any deadline for the completion?

**Comment by Rajat2024** [comment]
@MaYaNkKashyap681 no any deadline

**Comment by NehaShrama** [comment]
@Rajat2024 I would like to add a dark theme. Please assign it to me under GSSoC'23.

**Comment by Rajat2024** [comment]
@NehaShrama create a new issue then i will assign you.
i am clossing this issue
