### ISSUE TITLE
Login page design

### ISSUE THREAD

**Issue by k-deepak04** [Rajat2024/NoteBook#85]
**Describe the bug**
Login, signing page for we aren't looking good the text fields are so huge.

**To Reproduce**
1. Go to '

**Expected behavior**
It should be center specific and short

**Screenshots**
![image](https://github.com/Rajat2024/NoteBook/assets/96341431/0bc41f92-264a-4378-b3f2-b6b905fb8eb1)
![image](https://github.com/Rajat2024/NoteBook/assets/96341431/41b31b41-770d-4baa-b1f0-509bdf0d6369)

**Desktop (please complete the following information):**
 desktop screen 16 inch not looking good
**Smartphone (please complete the following information):**
 on mobile it's looking good i tested it on Iphone 12 pro

**Additional context**

**Comment by k-deepak04** [comment]
@Rajat2024 may i start resolving this issue?

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by sakshimaluskar2** [comment]
I am GSSOC '23 Contributor. I want to work on this issue. @Rajat2024 please assign me this issue.
