### ISSUE TITLE
Redesign the Footer Section

### ISSUE THREAD

**Issue by SagarPatil007** [Rajat2024/NoteBook#92]
I want to redesign the footer section and make responsive it and please assign me this task @Rajat2024

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.

**Comment by ssp1810** [comment]
Hey, I am a GSSoC'23 contributor. I want to work on this issue. Please, assign this task to me.
