### ISSUE TITLE
Email validation is not done in login page

### ISSUE THREAD

**Issue by kumar007ambi** [Rajat2024/NoteBook#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LaxmanSingh07** [comment]
please assign me this issue I will work on it.

**Comment by Apreksha** [comment]
Hey @Rajat2024, I'm a GSSoC'23 contributor and a full stack developer. I can add the email validation in login page. Could you please assign this task to me?

**Comment by VishalJx** [comment]
Greeting,
I would like to help adding email validation feature in login page. Kindly assign me this task under GSSOC'23.
Thank You.
