### ISSUE TITLE
While clicking on your notes button without login, there should be a msg or a popup to login first or signup

### ISSUE THREAD

**Issue by Urmilasc** [Rajat2024/NoteBook#97]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Urmilasc** [comment]
Hello Rajat, can you please assign this issue to me, show I can able to utilize my skills , please add a label of GSSoC

**Comment by Apreksha** [comment]
Hey @Rajat2024, I'm a GSSoC'23 contributor and a full stack developer. I can add a message or a popup to login first whenever the user clicks on "Your notes" button without being logged in. Could you please assign this task to me?
